development:
  adapter: mysql
  host: 127.0.0.1
  username: procon
  password: procon
  database: procon_dev
  port: 3306

test:
  adapter: mysql
  host: 127.0.0.1
  username: procon
  password: procon
  database: procon_test
  port: 3306
    
production:
  adapter: mysql
  host: 127.0.0.1
  username: procon
  password: procon
  database: procon_dev
  port: 3306
  
users:
  adapter: mysql
  host: 127.0.0.1
  username: root
  password: 
  database: ae_users
  port: 3306
